[package]
name = "dutchess_engine"
version = "0.1.0"
edition = "2021"
authors = ["Bill Cipher"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.17"
log = "0.4.19"
