[package]
name = "dutchess_core"
version = "0.1.0"
edition = "2021"
build = "src/build/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.17"
log = "0.4.22"
rand = "0.8.5"
