[package]
name = "dutchess_move_gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess = "3.2.0"
dutchess_core = { version = "0.1.0", path = "../dutchess_core" }
